blank_issues_enabled: true
contact_links:
  - name: Need help with your setup?
    url: https://github.com/evcc-io/evcc/discussions/categories/need-help
    about: Our community discussions will help you.
